# Default configuration for LangChain & LangGraph Project
# This file contains the default settings for the project
# Override these settings by creating a local.yaml file or setting environment variables

# Model configuration
model:
  provider: "openai"  # openai, anthropic, huggingface, local
  model_name: "gpt-3.5-turbo"
  temperature: 0.7
  max_tokens: null  # null means no limit
  api_key: null  # Set via environment variable OPENAI_API_KEY
  api_base: null  # Optional custom API base URL
  timeout: 30  # Request timeout in seconds
  max_retries: 3  # Maximum number of retries

# Vector store configuration
vector_store:
  provider: "chroma"  # chroma, pinecone, weaviate, faiss
  collection_name: "default"
  persist_directory: "./data/vectorstore"  # Directory to persist vector data
  embedding_model: "text-embedding-ada-002"  # OpenAI embedding model
  chunk_size: 1000  # Text chunk size for document processing
  chunk_overlap: 200  # Overlap between chunks

# Agent configuration
agent:
  memory_window: 10  # Number of messages to keep in memory
  max_iterations: 5  # Maximum iterations for agent execution
  enable_tools: true  # Whether to enable tools for agents
  tool_timeout: 30  # Timeout for tool execution in seconds
  verbose: false  # Enable verbose logging for agents

# Graph configuration
graph:
  max_steps: 100  # Maximum steps in a workflow
  enable_visualization: true  # Enable graph visualization
  output_format: "json"  # json, yaml, text
  save_intermediate: false  # Save intermediate results

# Logging configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_path: "./logs/app.log"  # Log file path (null for console only)
  max_file_size: 10485760  # 10MB in bytes
  backup_count: 5  # Number of backup log files to keep

# Development settings
development:
  debug: false
  hot_reload: false
  profiling: false

# Production settings
production:
  debug: false
  optimize: true
  cache_enabled: true
  rate_limiting: true

# Tool configurations
tools:
  # Web search tools
  web_search:
    enabled: true
    provider: "duckduckgo"  # duckduckgo, google, bing
    max_results: 5
    timeout: 10
  
  # Wikipedia tool
  wikipedia:
    enabled: true
    language: "en"
    max_results: 3
  
  # File system tools
  file_system:
    enabled: true
    allowed_extensions: [".txt", ".md", ".json", ".yaml", ".csv"]
    max_file_size: 5242880  # 5MB in bytes
    base_directory: "./data"
  
  # Calculator tool
  calculator:
    enabled: true
    precision: 10

# Security settings
security:
  api_key_validation: true
  rate_limit_per_minute: 60
  max_request_size: 1048576  # 1MB in bytes
  allowed_origins: ["*"]  # CORS origins
  
# Cache settings
cache:
  enabled: true
  backend: "memory"  # memory, redis, file
  ttl: 3600  # Time to live in seconds
  max_size: 1000  # Maximum number of cached items

# Database settings (if needed)
database:
  enabled: false
  url: "sqlite:///./data/app.db"
  pool_size: 5
  max_overflow: 10
  echo: false  # Log SQL queries

# Monitoring and metrics
monitoring:
  enabled: false
  metrics_endpoint: "/metrics"
  health_endpoint: "/health"
  
# Feature flags
features:
  experimental_features: false
  beta_features: false
  advanced_logging: false
  performance_monitoring: false